config/routes.rb
Rails.application.routes.draw do

  resources :members

  root "members#index"

  get "ajax" => "members#ajax"

  post "team_view" => "members#team_view"

  

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :all_members, only: [:index, :create, :update, :destroy]
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  include MembersHelper

  def ajax
  end

  def team_view
    @teams = team_assign(params[:size])    
    @members = Member.order(:team)
    @team_names = ["Sinister Blade", "Humanity", "Divine Elegence", "Heirs of the Sun", "Eliminator", "Arcane Fire", "Beryllium", "Cognitive Dissonance", "End Love", "Outlaw Gun", "Error 404", "Primal Rage", "Hope of Glory", "Reflective Hearts", "Grey Cell", "Undefined Method", "Wyrm", "Midnight Sun", "Double Echo", "Third Estate", "Nova Corps", "Obtenebration", "Cup of Kings", "Ten Foot Pole", "Liquid Rain", "Shining Alma", "Network Node","Delicate Fist", "Chronolock", "Terminal Button"]
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.create(member_params)
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    @member.update(member_params)
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
  end

  private
    def all_members
      @members = Member.all
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :team, :leader)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper

	def team_assign(size)
		members = Member.all
		pool = []
		members.each do | member |
			pool.push(member)
		end
		pool.shuffle!

		size = size.to_i

		if size == 0
			size = 1
		end
		
		teams = pool.length / size
		leftover = pool.length % size

		team_it = 1
		total_teams = 0


			teams.times do
				leadership = 0
				size.times do
					x = Member.find(pool[0].id)
					x.team = team_it
					if leadership == 0
						x.leader = true
					else
						x.leader = false
					end
					x.save
					pool.shift
					leadership = 1
				end
				team_it += 1
			end

			total_teams = team_it -1
			
			if leftover > size / 2
				leadership = 0
				pool.each do | member |
					member.team = team_it
					if leadership == 0
						member.leader = true
					else
						member.leader = false
					end
					member.save
					leadership = 1
				end
				total_teams += 1
			else
				team_it = 1
				leftover.times do
					x = Member.find(pool[0].id)
					x.team = team_it
					x.leader = false
					x.save
					pool.shift
					if team_it < teams
						team_it += 1
					else
						team_it = 1
					end
				end
			end


		return total_teams
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamBuilder</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav centerize">
      	<li>
			  <%= form_tag('/team_view') do %>
			      <%#= number_field_tag :size, placeholder: "Enter team size" %>
			      <%= select_tag "size", options_for_select(1..Member.all.length), prompt: "Enter team size" %>
			      <%= submit_tag "Create Team" %>
			  <% end %>
		</li>
      </ul>
    </div>
  </div>
</nav>



<div class="container text-center buffer background-color" style="height:100%">
	<%= yield %>
<div>

</body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, remote: true do |f| %>

    <%= f.text_field :name, placeholder: "Name" %>
    <%= f.number_field :team, value: 0, class: "cant-see-me"  %>
    <%= f.check_box :leader, placeholder: false, class: "cant-see-me"  %>

    <%= f.button :submit %>

<% end %>

app/views/members/_member.html.erb
<!-- _member.html.erb -->

<ul>
		<div class="col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
				<% if member.leader == true %>
					<b><%= member.name %></b>
				<%else%>
					<%= member.name %>
				<%end%>
				</div>
				<%= link_to "Rename", edit_member_path(member), remote: true %><br />
				<%= link_to "Kick Out", member, remote: true, method: :delete, data: { confirm: 'Are you sure?'} %>
			</div>
		</div>
</ul>

app/views/members/ajax.html.erb
<!-- ajax.html.erb -->

<script type="text/javascript">
	function loadMembers(){
		$.getJSON("/members.json", function(data){
			var output = "";
			$.each(data, function (index) {
				output += "<b><i>" + data[index].name + " is on Team " + data[index].team + "</i></b><br>";
			});
			$("#members").html(output);
		});
	}

</script>

<div id="members">
	<a href="javascript:loadMembers();">Content words</a>
</div>

app/views/members/create.js.erb
// create.js.erb

$('#members').html("<%= j (render @members) %>");
$('#member-form').slideUp(350);

app/views/members/destroy.js.erb
// destroy.js.erb

$('#members').html("<%= j (render @members) %>");

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/edit.js.erb
// edit.js.erb

$('#member-form').html("<%= j (render 'form') %>");
$('#member-form').slideDown(350);

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>The <u>Essence</u> of our Days in in the <i>style</i>...</h1>
<h2>it is both "classic" and fresh.</h2><br />

<%= link_to 'New Teammate', new_member_path, remote: true %>

<div id="member-form" style="display:none;"></div>

<div id="members">
    <%= render @members %>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/new.js.erb
// new.js.erb

$('#member-form').html("<%= j (render 'form') %>");
$('#member-form').slideDown(350);

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @member.team %>
</p>

<p>
  <strong>Leader:</strong>
  <%= @member.leader %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>

app/views/members/team_view.html.erb
<!-- team_view.html.erb -->

<br/>
<% if @teams == 1 %>
	You made 1 team.
<%else%>
	<h3>Gracious leader, you have commanded the assembly of <%= @teams %> loyal gatherings.</h3>
<%end%>
<br/><br/>

<% team_it = 1 %>
<% team_names = @team_names.shuffle %>

	<% @teams.times do %>
	<div class="col-md-4 team-display">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<b><%= team_names[team_it-1] %></b><br />
			</div>
			<div class="panel-body">
				<% @members.each do | member | %>
					<% if member.team == team_it && member.leader == true %>
						<b>Leader: </b><%= member.name %><br />
					<%end%>
				<%end%>
				<% @members.each do | member | %>
					<% if member.team == team_it && member.leader == false %>
						<%= member.name %><br />
					<%end%>
				<%end%>
				<% team_it += 1 %>
			</div>
		</div>
	</div>
	<%end%>

app/views/members/update.js.erb
// update.js.erb

$('#members').html("<%= j (render @members) %>");
$('#member-form').slideUp(350);